/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "var(--color-surface-container-low, #1a1b21)",
        "surface-bright": "var(--color-surface-bright, #38393f)",
        "inverse-surface": "var(--color-inverse-surface, #e3e1e9)",
        "on-primary-fixed-variant": "#3323cc",
        "on-primary": "var(--color-on-primary, #1d00a5)",
        "error-container": "var(--color-error-container, #93000a)",
        "tertiary-container": "var(--color-tertiary-container, #006e4b)",
        "surface-tint": "#c3c0ff",
        "on-surface-variant": "var(--color-on-surface-variant, #c7c4d8)",
        "outline-variant": "var(--color-outline-variant, #464555)",
        "primary-container": "var(--color-primary-container, #4f46e5)",
        "primary": "var(--color-primary, #c3c0ff)",
        "on-background": "var(--color-on-background, #e3e1e9)",
        "tertiary": "var(--color-tertiary, #4edea3)",
        "on-primary-fixed": "#0f0069",
        "secondary-fixed-dim": "#b4c5ff",
        "on-surface": "var(--color-on-surface, #e3e1e9)",
        "primary-fixed-dim": "#c3c0ff",
        "secondary-container": "var(--color-secondary-container, #0053db)",
        "on-tertiary-container": "var(--color-on-tertiary-container, #67f4b7)",
        "tertiary-fixed-dim": "#4edea3",
        "inverse-on-surface": "var(--color-inverse-on-surface, #2f3036)",
        "on-tertiary-fixed": "#002113",
        "on-secondary": "#002a78",
        "secondary": "var(--color-secondary, #b4c5ff)",
        "outline": "var(--color-outline, #918fa1)",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary-fixed-variant": "#003ea8",
        "inverse-primary": "#4d44e3",
        "on-tertiary-fixed-variant": "#005236",
        "primary-fixed": "#e2dfff",
        "on-error": "#690005",
        "surface-container-lowest": "var(--color-surface-container-lowest, #0d0e13)",
        "surface-dim": "var(--color-surface-dim, #121318)",
        "on-error-container": "var(--color-on-error-container, #ffdad6)",
        "secondary-fixed": "#dbe1ff",
        "on-tertiary": "#003824",
        "error": "var(--color-error, #ffb4ab)",
        "surface-container-highest": "var(--color-surface-container-highest, #34343a)",
        "surface-container-high": "var(--color-surface-container-high, #292a2f)",
        "surface-container": "var(--color-surface-container, #1e1f25)",
        "on-secondary-container": "var(--color-on-secondary-container, #cdd7ff)",
        "surface-variant": "var(--color-surface-variant, #34343a)",
        "on-primary-container": "var(--color-on-primary-container, #dad7ff)",
        "surface": "var(--color-surface, #121318)",
        "on-secondary-fixed": "#00174b",
        "background": "var(--color-background, #121318)",
        
        // Brand accents
        oryn: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        }
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "margin": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "gutter": "1rem",
        "margin-desktop": "2rem",
        "space-sm": "0.5rem",
        "gutter-desktop": "1.5rem"
      },
      fontFamily: {
        sans: ["Geist", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "label-md": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-sm": ["Geist", "sans-serif"]
      }
    }
  },
  plugins: [],
}
